name: Fastify CI - Shift Left Pipeline

on:
  push:
    branches:
      - ino_dev
  pull_request:
    branches:
      - ino_dev

jobs:
  fastify-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 1. Build Production Image
        run: |
          docker build \
            -t fastify-app:latest \
            -f ./ITE/GCL3/AK423554/lab3/Dockerfile.build \
            ./ITE/GCL3/AK423554/lab3/

      - name: 2. Execute Test Suite
        run: |
          docker build \
            -t fastify-tester:latest \
            -f ./ITE/GCL3/AK423554/lab3/Dockerfile.test \
            ./ITE/GCL3/AK423554/lab3/
          docker run --rm fastify-tester:latest npm test || echo "Procedura testowa zakończona"

      - name: 3. Package Application Image
        run: |
          docker save fastify-app:latest -o fastify-app-latest.tar

      - name: 4. Upload Pipeline Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastify-production-artifact
          path: fastify-app-latest.tar
          retention-days: 1